Pagination for properties
keboola/google-analytics-extractor pull request #98
Opened 2022-11-08 14:04 UTC by AdamVyborny

JIRA: https://keboola.atlassian.net/browse/COM-1712

Takhle to projde včas, testováno přes tag přímo na tom problematickém velkém projektu z ticketu

2022-11-08 14:45 UTC, ondrajodas commented
dej mě na review až projdou testy ;)

2022-11-08 15:49 UTC, AdamVyborny commented
@ondrajodas už 🙏

2022-11-09 08:09 UTC, ondrajodas requested changes

2022-11-09 08:09 UTC, ondrajodas commented on src/GoogleAnalytics/Client.php
> +            $url = sprintf('%s?pageSize=200', self::ACCOUNT_PROPERTIES_URL);
prosím nějjaký test na to... zkus ten pageSize dát spíš jako parametr s defaultní hodnotou přes konstantu a v testu tu přepsat na 1 a otestovat to

2022-11-11 09:05 UTC, ondrajodas approved these changes
super

2022-11-11 09:16 UTC, merged